export default {
    id: null,
    positions: [],
    start_form: null,
    start_to: null,
    start_all: false,
    duration_from: null,
    duration_to: null,
    duration_all: false,
    salary: null,
    city: '',
    city_id: null,
    country: '',
    country_id: null,
    full_search: true,
    latitude: '',
    longitude: '',
    booking: '',
    booking_id: null,
    booking_hour: null,
    conditions: [],
    dates: [],
    comment:'',
    name:'',
};